# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_user_last_name'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='user_travel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.User'),
        ),
    ]
