# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_travel_user_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='user_travel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_user', to='login_app.User'),
        ),
    ]
