# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20170530_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='created_by',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
